# Kmeans Project

## Data Preprocessing

In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_excel("DataSet.xlsx")


In [3]:
df.shape


(549, 44)

In [4]:
df.head()

1       2      3       4       5       6      7      8      9      10  \
0   2.167  49.353  3.164  83.844  20.932  16.184  6.360  1.450  5.130  3.786   
1  15.824  44.955  3.322  95.863   5.706  16.331  6.373  5.645  4.790  3.798   
2  28.097  48.948  3.051  90.796   6.652  16.670  6.334  1.460  5.043  7.772   
3  24.748  47.256  3.272  93.048  26.950  17.235  6.339  7.797  5.193  4.332   
4  15.331  49.245  3.470  94.053  19.889  18.063  6.333  6.443  5.295  7.343   

   ...      35      36      37      38      39     40      41      42      43  \
0  ...  12.074  14.244   6.365  55.938  23.980  1.157  10.606   8.810  17.961   
1  ...  11.802  18.812  14.661  61.358   2.987  0.008   4.662  25.630  19.301   
2  ...   7.748  26.991  12.869  53.250  32.902  0.008  16.964  13.839  19.145   
3  ...  13.722  12.555  16.087  56.152  15.237  0.007   7.341  26.700  17.457   
4  ...  13.928  15.929  17.560  54.995  17.373  0.008  16.687   7.732  14.419   

        44  
0  145.040  
1  145.060  
2  142.669  
3  113.355  
4  146.397  

[5 rows x 44 columns]

In [5]:
df1 = df.T

In [6]:
df1

0        1        2        3        4        5       6        7    \
1     2.167   15.824   28.097   24.748   15.331    1.692  22.931   22.460   
2    49.353   44.955   48.948   47.256   49.245   50.953  47.964   49.829   
3     3.164    3.322    3.051    3.272    3.470    3.557   3.058    3.586   
4    83.844   95.863   90.796   93.048   94.053   95.947  67.416   78.401   
5    20.932    5.706    6.652   26.950   19.889    4.578   3.496    6.201   
6    16.184   16.331   16.670   17.235   18.063   17.679  17.531   18.910   
7     6.360    6.373    6.334    6.339    6.333    5.998   6.043    6.337   
8     1.450    5.645    1.460    7.797    6.443    2.457   2.541    3.881   
9     5.130    4.790    5.043    5.193    5.295    6.029   5.628    4.061   
10    3.786    3.798    7.772    4.332    7.343    6.608   6.817    6.734   
11   21.427   21.489   21.457   21.318   21.273   21.806  21.252   21.464   
12   35.265   33.563   35.308   34.893   34.732   28.510  34.853   34.702   
13   84.333   84.561   82.259   98.180   70.172   67.445  73.063   77.070   
14   32.492   31.627    0.008    0.009    0.009    0.010   0.009    0.009   
15   36.683   36.517   35.467   36.785   36.753   36.570  36.781   36.791   
16   81.591   62.527   87.876   78.453   81.845   72.323  60.209   76.608   
17   21.477   19.121   22.776   22.410   21.818   24.315  23.210   16.994   
18   21.522   18.172   22.892   21.809   21.693   23.862  23.051   16.173   
19   38.473   10.540   41.939   59.182   55.639   50.687  62.401   45.222   
20   38.473   10.540   41.939   59.182   55.639   50.687  62.401   45.222   
21   40.942   41.374   41.280   31.222   29.330   41.168  41.028   40.946   
22    6.505    6.867    7.120    6.773    6.257    9.074   8.471    7.272   
23   15.009   17.330   14.610   11.904   11.017   12.408  11.117    8.003   
24    2.984    3.011    3.047    6.670   28.995   24.749   3.069    3.059   
25   20.801   21.829   25.396   20.994   20.547   25.499  20.623   25.451   
26    0.073    0.073    0.071    0.073    0.075    1.220   0.073   31.365   
27   53.639   49.264   76.068   69.719   57.155   53.048  58.803   63.758   
28   55.766   45.721   50.450   46.547   54.209   40.126  49.154   49.610   
29   59.183   41.454   35.138   72.942   63.835   38.173  27.972   37.906   
30    2.284    8.914    2.852   12.945    3.024    2.911  16.238   13.283   
31    6.602   17.022   19.903    3.025    3.385   17.973   0.389   19.596   
32   40.640   33.025   34.633   37.137   36.071   39.130  37.541   40.287   
33   38.211   38.185   37.941   37.270   38.075   38.121  38.019   38.039   
34    0.004    0.000    5.241    1.778   18.515   18.458   0.112    5.804   
35   12.074   11.802    7.748   13.722   13.928   13.727  15.979   13.496   
36   14.244   18.812   26.991   12.555   15.929   22.486  14.014   27.909   
37    6.365   14.661   12.869   16.087   17.560   19.698  13.834   13.603   
38   55.938   61.358   53.250   56.152   54.995   53.939  53.326   59.441   
39   23.980    2.987   32.902   15.237   17.373   17.481  11.950   13.076   
40    1.157    0.008    0.008    0.007    0.008    1.480   0.008    0.008   
41   10.606    4.662   16.964    7.341   16.687    2.437   2.969   12.987   
42    8.810   25.630   13.839   26.700    7.732    0.014  34.977   28.477   
43   17.961   19.301   19.145   17.457   14.419   17.888  16.321   16.318   
44  145.040  145.060  142.669  113.355  146.397  145.831  95.285  147.871   

        8        9    ...     539     540     541     542     543     544  \
1    29.038    6.608  ...  11.977  17.238   3.630   2.866   0.410   0.398   
2    47.983   51.772  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3     3.351    3.201  ...   3.358   3.015   3.151   3.274   3.493   3.501   
4    95.797   95.983  ...  74.317  76.770  93.757  92.088  74.379  74.358   
5     5.328    5.307  ...   0.521   0.541   0.551   0.539   0.574   0.434   
6    18.236   15.876  ...  15.689  16.299  12.665  16.023  15.896  16.460   
7  

In [7]:
X = df.iloc[:,:].values

In [8]:
X

array([[2.16700e+00, 4.93530e+01, 3.16400e+00, ..., 8.81000e+00,
        1.79610e+01, 1.45040e+02],
       [1.58240e+01, 4.49550e+01, 3.32200e+00, ..., 2.56300e+01,
        1.93010e+01, 1.45060e+02],
       [2.80970e+01, 4.89480e+01, 3.05100e+00, ..., 1.38390e+01,
        1.91450e+01, 1.42669e+02],
       ...,
       [1.38000e-01,         nan, 3.29200e+00, ..., 1.40000e-02,
        1.29000e-01,         nan],
       [1.54000e-01,         nan, 3.23900e+00, ...,         nan,
        1.34000e-01,         nan],
       [1.56000e-01,         nan, 3.32600e+00, ...,         nan,
        1.64000e-01,         nan]])

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X = imputer.fit_transform(X)

In [10]:
X

array([[2.16700000e+00, 4.93530000e+01, 3.16400000e+00, ...,
        8.81000000e+00, 1.79610000e+01, 1.45040000e+02],
       [1.58240000e+01, 4.49550000e+01, 3.32200000e+00, ...,
        2.56300000e+01, 1.93010000e+01, 1.45060000e+02],
       [2.80970000e+01, 4.89480000e+01, 3.05100000e+00, ...,
        1.38390000e+01, 1.91450000e+01, 1.42669000e+02],
       ...,
       [1.38000000e-01, 3.65454318e+01, 3.29200000e+00, ...,
        1.40000000e-02, 1.29000000e-01, 8.72560452e+01],
       [1.54000000e-01, 3.65454318e+01, 3.23900000e+00, ...,
        3.61680183e+01, 1.34000000e-01, 8.72560452e+01],
       [1.56000000e-01, 3.65454318e+01, 3.32600000e+00, ...,
        3.61680183e+01, 1.64000000e-01, 8.72560452e+01]])

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [12]:
X

array([[6.02119046e-02, 7.58295017e-01, 3.97149126e-02, ...,
        1.31852672e-01, 6.79480836e-01, 9.35385885e-01],
       [4.52350188e-01, 6.89977631e-01, 4.20415556e-02, ...,
        3.83585016e-01, 7.30483767e-01, 9.35514869e-01],
       [8.04749189e-01, 7.52003852e-01, 3.80509211e-02, ...,
        2.07117949e-01, 7.24546112e-01, 9.20094932e-01],
       ...,
       [1.95250811e-03, 5.59345592e-01, 4.15997880e-02, ...,
        2.09527515e-04, 7.61237773e-04, 5.62728028e-01],
       [2.41192178e-03, 5.59345592e-01, 4.08193318e-02, ...,
        5.41299644e-01, 9.51547216e-04, 5.62728028e-01],
       [2.46934849e-03, 5.59345592e-01, 4.21004580e-02, ...,
        5.41299644e-01, 2.09340387e-03, 5.62728028e-01]])

In [13]:
X1 =X.T
X1

array([[6.02119046e-02, 4.52350188e-01, 8.04749189e-01, ...,
        1.95250811e-03, 2.41192178e-03, 2.46934849e-03],
       [7.58295017e-01, 6.89977631e-01, 7.52003852e-01, ...,
        5.59345592e-01, 5.59345592e-01, 5.59345592e-01],
       [3.97149126e-02, 4.20415556e-02, 3.80509211e-02, ...,
        4.15997880e-02, 4.08193318e-02, 4.21004580e-02],
       ...,
       [1.31852672e-01, 3.83585016e-01, 2.07117949e-01, ...,
        2.09527515e-04, 5.41299644e-01, 5.41299644e-01],
       [6.79480836e-01, 7.30483767e-01, 7.24546112e-01, ...,
        7.61237773e-04, 9.51547216e-04, 2.09340387e-03],
       [9.35385885e-01, 9.35514869e-01, 9.20094932e-01, ...,
        5.62728028e-01, 5.62728028e-01, 5.62728028e-01]])

## converting Data format to TSLearn Time Series

In [17]:
from tslearn.utils import to_time_series_dataset


In [33]:
X2 = to_time_series_dataset(X1)

## Clustering Using Euclidean Metric

In [34]:
from tslearn.clustering import TimeSeriesKMeans
km =TimeSeriesKMeans(n_clusters=3, metric="euclidean", random_state=0)
km.fit_predict(X2)

array([0, 1, 0, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 2, 2, 2, 1, 2,
       2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0],
      dtype=int64)

## Clustering Using softdtw Metric

In [41]:
km2 =TimeSeriesKMeans(n_clusters=3, metric="softdtw", random_state=0)
km2.fit_predict(X2)

array([0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 2, 1, 0, 1, 1, 1, 2, 2, 1, 1, 2, 0, 1, 1, 1, 0, 2, 2, 2, 0, 1],
      dtype=int64)